// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SatRural.Infrastructure.Persistence;

#nullable disable

namespace SatRural.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SatRural.Domain.Entities.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("SensorId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phenomenon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SensorType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ThresholdValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AlertRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Temperatura elevada",
                            Operator = ">=",
                            Phenomenon = "Ola de calor",
                            RiskLevel = "YELLOW",
                            SensorType = "TEMPERATURE",
                            ThresholdValue = 32m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Temperatura muy elevada",
                            Operator = ">=",
                            Phenomenon = "Ola de calor",
                            RiskLevel = "ORANGE",
                            SensorType = "TEMPERATURE",
                            ThresholdValue = 35m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Temperatura extremadamente elevada",
                            Operator = ">=",
                            Phenomenon = "Ola de calor",
                            RiskLevel = "RED",
                            SensorType = "TEMPERATURE",
                            ThresholdValue = 38m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Temperatura baja",
                            Operator = "<=",
                            Phenomenon = "Helada",
                            RiskLevel = "YELLOW",
                            SensorType = "TEMPERATURE",
                            ThresholdValue = 8m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Temperatura muy baja",
                            Operator = "<=",
                            Phenomenon = "Helada",
                            RiskLevel = "ORANGE",
                            SensorType = "TEMPERATURE",
                            ThresholdValue = 4m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Temperatura extremadamente baja",
                            Operator = "<=",
                            Phenomenon = "Helada",
                            RiskLevel = "RED",
                            SensorType = "TEMPERATURE",
                            ThresholdValue = 0m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Humedad baja",
                            Operator = "<=",
                            Phenomenon = "Sequía",
                            RiskLevel = "YELLOW",
                            SensorType = "HUMIDITY",
                            ThresholdValue = 40m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Humedad muy baja",
                            Operator = "<=",
                            Phenomenon = "Sequía",
                            RiskLevel = "ORANGE",
                            SensorType = "HUMIDITY",
                            ThresholdValue = 30m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Humedad extremadamente baja",
                            Operator = "<=",
                            Phenomenon = "Sequía",
                            RiskLevel = "RED",
                            SensorType = "HUMIDITY",
                            ThresholdValue = 20m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Velocidad del viento elevada",
                            Operator = ">=",
                            Phenomenon = "Tormenta",
                            RiskLevel = "YELLOW",
                            SensorType = "WIND_SPEED",
                            ThresholdValue = 30m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Velocidad del viento muy elevada",
                            Operator = ">=",
                            Phenomenon = "Tormenta",
                            RiskLevel = "ORANGE",
                            SensorType = "WIND_SPEED",
                            ThresholdValue = 50m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Velocidad del viento extremadamente elevada",
                            Operator = ">=",
                            Phenomenon = "Tormenta",
                            RiskLevel = "RED",
                            SensorType = "WIND_SPEED",
                            ThresholdValue = 70m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Nivel de lluvia elevado",
                            Operator = ">=",
                            Phenomenon = "Inundación",
                            RiskLevel = "YELLOW",
                            SensorType = "RAINFALL",
                            ThresholdValue = 15m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Nivel de lluvia muy elevado",
                            Operator = ">=",
                            Phenomenon = "Inundación",
                            RiskLevel = "ORANGE",
                            SensorType = "RAINFALL",
                            ThresholdValue = 30m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Nivel de lluvia extremadamente elevado",
                            Operator = ">=",
                            Phenomenon = "Inundación",
                            RiskLevel = "RED",
                            SensorType = "RAINFALL",
                            ThresholdValue = 50m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Nivel del río elevado",
                            Operator = ">=",
                            Phenomenon = "Inundación",
                            RiskLevel = "YELLOW",
                            SensorType = "RIVER_LEVEL",
                            ThresholdValue = 60m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Nivel del río muy elevado",
                            Operator = ">=",
                            Phenomenon = "Inundación",
                            RiskLevel = "ORANGE",
                            SensorType = "RIVER_LEVEL",
                            ThresholdValue = 75m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Nivel del río extremadamente elevado",
                            Operator = ">=",
                            Phenomenon = "Inundación",
                            RiskLevel = "RED",
                            SensorType = "RIVER_LEVEL",
                            ThresholdValue = 90m
                        });
                });

            modelBuilder.Entity("SatRural.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Binnacle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateHour")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdMovimentType")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Binnacles");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Communities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "Guatemala",
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Department = "Guatemala",
                            Description = "Comunidad inicial del sistema de monitoreo.",
                            IsActive = true,
                            Latitude = 14.634915m,
                            Longitude = -90.506882m,
                            Municipality = "Guatemala",
                            Name = "Comunidad El Pinar"
                        });
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Event", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AlertId")
                        .HasColumnType("bigint");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AlertId");

                    b.HasIndex("CommunityId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "USER"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "USERCONSULTA"
                        });
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("InstallationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CommunityId");

                    b.ToTable("Sensors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "TEMP-001",
                            CommunityId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Temperatura Ambiente",
                            Type = "TEMPERATURE",
                            Unit = "°C"
                        },
                        new
                        {
                            Id = 2,
                            Code = "HUM-001",
                            CommunityId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Humedad Relativa",
                            Type = "HUMIDITY",
                            Unit = "%"
                        },
                        new
                        {
                            Id = 3,
                            Code = "WIND-001",
                            CommunityId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Velocidad del Viento",
                            Type = "WIND_SPEED",
                            Unit = "km/h"
                        },
                        new
                        {
                            Id = 4,
                            Code = "RAIN-001",
                            CommunityId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nivel de Lluvia",
                            Type = "RAINFALL",
                            Unit = "mm/h"
                        },
                        new
                        {
                            Id = 5,
                            Code = "RIVER-001",
                            CommunityId = 1,
                            CreatedAt = new DateTime(2026, 8, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Nivel del Río",
                            Type = "RIVER_LEVEL",
                            Unit = "%"
                        });
                });

            modelBuilder.Entity("SatRural.Domain.Entities.SensorReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("SensorReadings");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Alert", b =>
                {
                    b.HasOne("SatRural.Domain.Entities.Community", "Community")
                        .WithMany("Alerts")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SatRural.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Alerts")
                        .HasForeignKey("SensorId");

                    b.Navigation("Community");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("SatRural.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Event", b =>
                {
                    b.HasOne("SatRural.Domain.Entities.Alert", "Alert")
                        .WithMany("Events")
                        .HasForeignKey("AlertId");

                    b.HasOne("SatRural.Domain.Entities.Community", "Community")
                        .WithMany("Events")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alert");

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("SatRural.Domain.Entities.Community", "Community")
                        .WithMany("Sensors")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Community");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.SensorReading", b =>
                {
                    b.HasOne("SatRural.Domain.Entities.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.User", b =>
                {
                    b.HasOne("SatRural.Domain.Entities.Rol", null)
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Alert", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Community", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Events");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.Sensor", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("SatRural.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
